// <auto-generated />
namespace Rental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tryForLoop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryForLoop));
        
        string IMigrationMetadata.Id
        {
            get { return "202307092028129_tryForLoop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
